from __future__ import annotations

import csv
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path

import pandas as pd

from orchestrator.db import ensure_db, fetch_runs


@dataclass(frozen=True)
class LeaderboardPaths:
    json_path: Path
    csv_path: Path
    html_path: Path


def _pacific_tz_name() -> str:
    return "America/Los_Angeles"


def _get_pacific_tz():
    try:
        from zoneinfo import ZoneInfo  # type: ignore

        return ZoneInfo(_pacific_tz_name())
    except Exception:
        return None


def _parse_iso_datetime(s: str | None) -> datetime | None:
    if not s:
        return None
    raw = str(s).strip()
    if not raw:
        return None
    if raw.endswith("Z"):
        raw = raw[:-1] + "+00:00"
    dt = datetime.fromisoformat(raw)
    if dt.tzinfo is None:
        dt = dt.replace(tzinfo=timezone.utc)
    return dt


def _format_created_at_pacific(s: str | None) -> str | None:
    dt = _parse_iso_datetime(s)
    if dt is None:
        return None if s is None else str(s)
    pacific_tz = _get_pacific_tz()
    if pacific_tz is None:
        # Fallback: keep in UTC if tz database isn't available.
        return dt.astimezone(timezone.utc).replace(microsecond=0).isoformat()
    return dt.astimezone(pacific_tz).replace(microsecond=0).isoformat()


def _df_to_markdown_table(df: pd.DataFrame) -> str:
    df = df.fillna("")
    cols = list(df.columns)
    if not cols:
        return "_(empty)_\n"

    header = "| " + " | ".join(cols) + " |"
    sep = "| " + " | ".join(["---"] * len(cols)) + " |"
    lines = [header, sep]
    for _, row in df.iterrows():
        vals = []
        for c in cols:
            v = str(row[c])
            v = v.replace("\n", " ").replace("|", "\\|")
            vals.append(v)
        lines.append("| " + " | ".join(vals) + " |")
    return "\n".join(lines) + "\n"


def write_root_leaderboard(*, df: pd.DataFrame, repo_root: Path, title: str = "TML-bench leaderboard") -> None:
    md_path = repo_root / "LEADERBOARD.md"
    html_path = repo_root / "LEADERBOARD.html"

    md = (
        f"# {title}\n\n"
        "This file is generated by the orchestrator from local run results.\n\n"
        "- Source DB (not committed): `results/results.sqlite`\n"
        "- Also generated: `results/leaderboard.json`, `results/leaderboard.csv`, `results/leaderboard.html`\n\n"
        f"- Timestamps are in US Pacific (`{_pacific_tz_name()}`)\n\n"
    )
    if not df.empty and {"competition_id", "provider", "model_id", "mode", "score_raw", "run_id"}.issubset(set(df.columns)):
        df_sorted = df.copy()
        df_sorted["score_raw"] = pd.to_numeric(df_sorted["score_raw"], errors="coerce")
        if "created_at" in df_sorted.columns:
            df_sorted["_created_at_dt"] = df_sorted["created_at"].map(_parse_iso_datetime)
        df_sorted = df_sorted.sort_values(
            by=["competition_id", "score_raw", "_created_at_dt" if "_created_at_dt" in df_sorted.columns else "created_at"],
            ascending=[True, True, False],
            na_position="last",
        )
        group_cols = ["competition_id", "provider", "model_id", "mode"]
        best = df_sorted.groupby(group_cols, dropna=False).head(1).copy()
        if "_created_at_dt" in best.columns:
            best = best.drop(columns=["_created_at_dt"])
        best = best.rename(
            columns={
                "run_id": "best_run_id",
                "score_raw": "best_score_raw",
                "runtime_seconds": "best_runtime_seconds",
                "budget_time_seconds": "budget_time_seconds",
            }
        )
        best = best[
            [
                "competition_id",
                "provider",
                "model_id",
                "mode",
                "metric_name",
                "best_score_raw",
                "best_runtime_seconds",
                "budget_time_seconds",
                "best_run_id",
            ]
        ]
        md += "## Best by model (per competition)\n\n"
        md += _df_to_markdown_table(best)
        md += "\n## All runs\n\n"
    md += _df_to_markdown_table(df)
    md_path.write_text(md, encoding="utf-8")

    html = (
        f"<h1>{title}</h1>\n"
        "<p>Generated by the orchestrator from local run results.</p>\n"
        "<ul>"
        "<li>Source DB (not committed): <code>results/results.sqlite</code></li>"
        "<li>Also generated: <code>results/leaderboard.json</code>, <code>results/leaderboard.csv</code>, <code>results/leaderboard.html</code></li>"
        f"<li>Timestamps are in US Pacific (<code>{_pacific_tz_name()}</code>)</li>"
        "</ul>\n"
    )
    if not df.empty and {"competition_id", "provider", "model_id", "mode", "score_raw", "run_id"}.issubset(set(df.columns)):
        df_sorted = df.copy()
        df_sorted["score_raw"] = pd.to_numeric(df_sorted["score_raw"], errors="coerce")
        if "created_at" in df_sorted.columns:
            df_sorted["_created_at_dt"] = df_sorted["created_at"].map(_parse_iso_datetime)
        df_sorted = df_sorted.sort_values(
            by=["competition_id", "score_raw", "_created_at_dt" if "_created_at_dt" in df_sorted.columns else "created_at"],
            ascending=[True, True, False],
            na_position="last",
        )
        group_cols = ["competition_id", "provider", "model_id", "mode"]
        best = df_sorted.groupby(group_cols, dropna=False).head(1).copy()
        if "_created_at_dt" in best.columns:
            best = best.drop(columns=["_created_at_dt"])
        best = best.rename(
            columns={
                "run_id": "best_run_id",
                "score_raw": "best_score_raw",
                "runtime_seconds": "best_runtime_seconds",
            }
        )
        html += "<h2>Best by model (per competition)</h2>\n"
        html += best[
            [
                "competition_id",
                "provider",
                "model_id",
                "mode",
                "metric_name",
                "best_score_raw",
                "best_runtime_seconds",
                "budget_time_seconds",
                "best_run_id",
            ]
        ].to_html(index=False, escape=True)
        html += "\n<h2>All runs</h2>\n"

    html += df.to_html(index=False, escape=True)
    html_path.write_text(html, encoding="utf-8")


def build_leaderboard(
    *,
    db_path: Path,
    out_paths: LeaderboardPaths,
    competition_id: str | None = None,
) -> pd.DataFrame:
    ensure_db(db_path)
    rows = fetch_runs(db_path, competition_id=competition_id)
    df_full = pd.DataFrame(rows)
    keep = [
        "run_id",
        "created_at",
        "competition_id",
        "status",
        "provider",
        "model_id",
        "mode",
        "temperature",
        "max_tokens",
        "metric_name",
        "score_raw",
        "runtime_seconds",
        "budget_time_seconds",
    ]
    if df_full.empty:
        df = pd.DataFrame(columns=keep)
    else:
        df = df_full[[c for c in keep if c in df_full.columns]].copy()

    # Sorting is done using parsed datetimes, but we display in US Pacific.
    if "created_at" in df.columns:
        df["_created_at_dt"] = df["created_at"].map(_parse_iso_datetime)

    # For Phase 2 we keep it simple: show all runs sorted by (competition_id, score_raw) where available.
    df["score_raw"] = pd.to_numeric(df.get("score_raw"), errors="coerce")
    sort_created = "_created_at_dt" if "_created_at_dt" in df.columns else "created_at"
    df = df.sort_values(by=["competition_id", "score_raw", sort_created], ascending=[True, True, False], na_position="last")

    if "created_at" in df.columns:
        df["created_at"] = df["created_at"].map(_format_created_at_pacific)
        if "_created_at_dt" in df.columns:
            df = df.drop(columns=["_created_at_dt"])

    out_paths.json_path.parent.mkdir(parents=True, exist_ok=True)
    out_paths.csv_path.parent.mkdir(parents=True, exist_ok=True)
    out_paths.html_path.parent.mkdir(parents=True, exist_ok=True)

    out_paths.json_path.write_text(df.to_json(orient="records", indent=2), encoding="utf-8")
    df.to_csv(out_paths.csv_path, index=False, quoting=csv.QUOTE_MINIMAL)

    out_paths.html_path.write_text(df.to_html(index=False, escape=True), encoding="utf-8")

    return df


def main() -> int:
    import argparse

    parser = argparse.ArgumentParser(description="Generate leaderboard files from the local results DB.")
    parser.add_argument("--db-path", default="results/results.sqlite")
    parser.add_argument("--competition-id", default=None)
    parser.add_argument("--per-competition", action="store_true", help="If set, leaderboard is filtered to --competition-id.")
    parser.add_argument("--write-root", action="store_true", help="If set, write LEADERBOARD.md/html at repo root.")
    args = parser.parse_args()

    repo_root = Path(__file__).resolve().parents[1]
    out_paths = LeaderboardPaths(
        json_path=repo_root / "results" / "leaderboard.json",
        csv_path=repo_root / "results" / "leaderboard.csv",
        html_path=repo_root / "results" / "leaderboard.html",
    )
    df = build_leaderboard(
        db_path=Path(args.db_path),
        out_paths=out_paths,
        competition_id=args.competition_id if args.per_competition else None,
    )
    if args.write_root:
        write_root_leaderboard(df=df, repo_root=repo_root)
    print(f"wrote: {out_paths.json_path}")
    print(f"wrote: {out_paths.csv_path}")
    print(f"wrote: {out_paths.html_path}")
    if args.write_root:
        print(f"wrote: {repo_root / 'LEADERBOARD.md'}")
        print(f"wrote: {repo_root / 'LEADERBOARD.html'}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
