from __future__ import annotations

import csv
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path

import pandas as pd

from orchestrator.db import ensure_db, fetch_runs, insert_run
from orchestrator.result import read_result_json


@dataclass(frozen=True)
class LeaderboardPaths:
    json_path: Path
    csv_path: Path
    html_path: Path


def _pacific_tz_name() -> str:
    return "America/Los_Angeles"


def _get_pacific_tz():
    try:
        from zoneinfo import ZoneInfo  # type: ignore

        return ZoneInfo(_pacific_tz_name())
    except Exception:
        return None


def _parse_iso_datetime(s: str | None) -> datetime | None:
    if not s:
        return None
    raw = str(s).strip()
    if not raw:
        return None
    if raw.endswith("Z"):
        raw = raw[:-1] + "+00:00"
    dt = datetime.fromisoformat(raw)
    if dt.tzinfo is None:
        dt = dt.replace(tzinfo=timezone.utc)
    return dt


def _format_created_at_pacific(s: str | None) -> str | None:
    dt = _parse_iso_datetime(s)
    if dt is None:
        return None if s is None else str(s)
    pacific_tz = _get_pacific_tz()
    if pacific_tz is None:
        # Fallback: keep in UTC if tz database isn't available.
        return dt.astimezone(timezone.utc).replace(microsecond=0).isoformat()
    return dt.astimezone(pacific_tz).replace(microsecond=0).isoformat()


def _df_to_markdown_table(df: pd.DataFrame) -> str:
    df = df.fillna("")
    cols = list(df.columns)
    if not cols:
        return "_(empty)_\n"

    header = "| " + " | ".join(cols) + " |"
    sep = "| " + " | ".join(["---"] * len(cols)) + " |"
    lines = [header, sep]
    for _, row in df.iterrows():
        vals = []
        for c in cols:
            v = str(row[c])
            v = v.replace("\n", " ").replace("|", "\\|")
            vals.append(v)
        lines.append("| " + " | ".join(vals) + " |")
    return "\n".join(lines) + "\n"


def _duplicate_submissions_df(df: pd.DataFrame) -> pd.DataFrame:
    if df.empty:
        return pd.DataFrame()

    needed = {"competition_id", "run_id", "provider", "model_id", "status", "score_raw", "normalized_submission_sha256"}
    if not needed.issubset(set(df.columns)):
        return pd.DataFrame()

    d = df.copy()
    d = d.fillna("")
    d = d[(d["status"] == "success") & (d["normalized_submission_sha256"].astype(str).str.strip() != "")]
    if d.empty:
        return pd.DataFrame()

    rows: list[dict[str, object]] = []
    for (competition_id, norm_sha), g in d.groupby(["competition_id", "normalized_submission_sha256"], dropna=False):
        n = int(len(g))
        if n <= 1:
            continue
        g = g.copy()
        g["score_raw"] = pd.to_numeric(g["score_raw"], errors="coerce")
        g = g.sort_values(by=["score_raw", "run_id"], ascending=[True, True], na_position="last")

        models = [f"{p}::{m}" for p, m in zip(g["provider"].astype(str), g["model_id"].astype(str), strict=False)]
        run_ids = [str(x) for x in g["run_id"].tolist()]
        rows.append(
            {
                "competition_id": str(competition_id),
                "normalized_submission_sha256": str(norm_sha),
                "count": n,
                "score_raw": float(g["score_raw"].iloc[0]) if pd.notna(g["score_raw"].iloc[0]) else "",
                "models": ", ".join(models[:5]) + ("…" if n > 5 else ""),
                "run_ids": ", ".join(run_ids[:5]) + ("…" if n > 5 else ""),
            }
        )

    if not rows:
        return pd.DataFrame()

    out = pd.DataFrame(rows)
    out = out.sort_values(by=["competition_id", "count"], ascending=[True, False], na_position="last")
    return out


def write_root_leaderboard(*, df: pd.DataFrame, repo_root: Path, title: str = "TML-bench leaderboard") -> None:
    md_path = repo_root / "LEADERBOARD.md"
    html_path = repo_root / "LEADERBOARD.html"

    md = (
        f"# {title}\n\n"
        "This file is generated by the orchestrator from local run results.\n\n"
        "- Source DB (not committed): `results/results.sqlite`\n"
        "- Also generated: `results/leaderboard.json`, `results/leaderboard.csv`, `results/leaderboard.html`\n\n"
        f"- Timestamps are in US Pacific (`{_pacific_tz_name()}`)\n\n"
    )
    if not df.empty and {"competition_id", "provider", "model_id", "mode", "score_raw", "run_id"}.issubset(set(df.columns)):
        df_sorted = df.copy()
        df_sorted["score_raw"] = pd.to_numeric(df_sorted["score_raw"], errors="coerce")
        if "created_at" in df_sorted.columns:
            df_sorted["_created_at_dt"] = df_sorted["created_at"].map(_parse_iso_datetime)
        df_sorted = df_sorted.sort_values(
            by=["competition_id", "score_raw", "_created_at_dt" if "_created_at_dt" in df_sorted.columns else "created_at"],
            ascending=[True, True, False],
            na_position="last",
        )
        group_cols = ["competition_id", "provider", "model_id", "mode"]
        best = df_sorted.groupby(group_cols, dropna=False).head(1).copy()
        if "_created_at_dt" in best.columns:
            best = best.drop(columns=["_created_at_dt"])
        best = best.rename(
            columns={
                "run_id": "best_run_id",
                "score_raw": "best_score_raw",
                "runtime_seconds": "best_runtime_seconds",
                "budget_time_seconds": "budget_time_seconds",
            }
        )
        if "submission_sha256" in best.columns:
            best = best.rename(columns={"submission_sha256": "best_submission_sha256"})
        if "normalized_submission_sha256" in best.columns:
            best = best.rename(columns={"normalized_submission_sha256": "best_normalized_submission_sha256"})

        best_cols = [
            "competition_id",
            "provider",
            "model_id",
            "mode",
            "metric_name",
            "best_score_raw",
            "best_runtime_seconds",
            "budget_time_seconds",
            "best_run_id",
        ]
        for extra in ["best_submission_sha256", "best_normalized_submission_sha256"]:
            if extra in best.columns:
                best_cols.append(extra)
        best = best[best_cols]
        md += "## Best by model (per competition)\n\n"
        md += _df_to_markdown_table(best)

        dup = _duplicate_submissions_df(df_sorted)
        if not dup.empty:
            md += "\n## Duplicate submissions (by normalized hash)\n\n"
            md += _df_to_markdown_table(dup)

        md += "\n## All runs\n\n"
    md += _df_to_markdown_table(df)
    md_path.write_text(md, encoding="utf-8")

    html = (
        f"<h1>{title}</h1>\n"
        "<p>Generated by the orchestrator from local run results.</p>\n"
        "<ul>"
        "<li>Source DB (not committed): <code>results/results.sqlite</code></li>"
        "<li>Also generated: <code>results/leaderboard.json</code>, <code>results/leaderboard.csv</code>, <code>results/leaderboard.html</code></li>"
        f"<li>Timestamps are in US Pacific (<code>{_pacific_tz_name()}</code>)</li>"
        "</ul>\n"
    )
    if not df.empty and {"competition_id", "provider", "model_id", "mode", "score_raw", "run_id"}.issubset(set(df.columns)):
        df_sorted = df.copy()
        df_sorted["score_raw"] = pd.to_numeric(df_sorted["score_raw"], errors="coerce")
        if "created_at" in df_sorted.columns:
            df_sorted["_created_at_dt"] = df_sorted["created_at"].map(_parse_iso_datetime)
        df_sorted = df_sorted.sort_values(
            by=["competition_id", "score_raw", "_created_at_dt" if "_created_at_dt" in df_sorted.columns else "created_at"],
            ascending=[True, True, False],
            na_position="last",
        )
        group_cols = ["competition_id", "provider", "model_id", "mode"]
        best = df_sorted.groupby(group_cols, dropna=False).head(1).copy()
        if "_created_at_dt" in best.columns:
            best = best.drop(columns=["_created_at_dt"])
        best = best.rename(
            columns={
                "run_id": "best_run_id",
                "score_raw": "best_score_raw",
                "runtime_seconds": "best_runtime_seconds",
            }
        )
        if "submission_sha256" in best.columns:
            best = best.rename(columns={"submission_sha256": "best_submission_sha256"})
        if "normalized_submission_sha256" in best.columns:
            best = best.rename(columns={"normalized_submission_sha256": "best_normalized_submission_sha256"})

        html += "<h2>Best by model (per competition)</h2>\n"
        best_cols = [
            "competition_id",
            "provider",
            "model_id",
            "mode",
            "metric_name",
            "best_score_raw",
            "best_runtime_seconds",
            "budget_time_seconds",
            "best_run_id",
        ]
        for extra in ["best_submission_sha256", "best_normalized_submission_sha256"]:
            if extra in best.columns:
                best_cols.append(extra)
        html += best[best_cols].to_html(index=False, escape=True)

        dup = _duplicate_submissions_df(df_sorted)
        if not dup.empty:
            html += "\n<h2>Duplicate submissions (by normalized hash)</h2>\n"
            html += dup.to_html(index=False, escape=True)

        html += "\n<h2>All runs</h2>\n"

    html += df.to_html(index=False, escape=True)
    html_path.write_text(html, encoding="utf-8")


def build_leaderboard(
    *,
    db_path: Path,
    out_paths: LeaderboardPaths,
    competition_id: str | None = None,
) -> pd.DataFrame:
    ensure_db(db_path)
    rows = fetch_runs(db_path, competition_id=competition_id)
    df_full = pd.DataFrame(rows)
    keep = [
        "run_id",
        "created_at",
        "competition_id",
        "status",
        "provider",
        "model_id",
        "mode",
        "temperature",
        "max_tokens",
        "metric_name",
        "score_raw",
        "runtime_seconds",
        "budget_time_seconds",
        "submission_sha256",
        "normalized_submission_sha256",
    ]
    if df_full.empty:
        df = pd.DataFrame(columns=keep)
    else:
        df = df_full[[c for c in keep if c in df_full.columns]].copy()

    # Sorting is done using parsed datetimes, but we display in US Pacific.
    if "created_at" in df.columns:
        df["_created_at_dt"] = df["created_at"].map(_parse_iso_datetime)

    # For Phase 2 we keep it simple: show all runs sorted by (competition_id, score_raw) where available.
    df["score_raw"] = pd.to_numeric(df.get("score_raw"), errors="coerce")
    sort_created = "_created_at_dt" if "_created_at_dt" in df.columns else "created_at"
    df = df.sort_values(by=["competition_id", "score_raw", sort_created], ascending=[True, True, False], na_position="last")

    if "created_at" in df.columns:
        df["created_at"] = df["created_at"].map(_format_created_at_pacific)
        if "_created_at_dt" in df.columns:
            df = df.drop(columns=["_created_at_dt"])

    def _short_sha(x: object) -> object:
        if x is None:
            return None
        s = str(x).strip()
        if not s:
            return ""
        return s[:16] + "…"

    if "submission_sha256" in df.columns:
        df["submission_sha256"] = df["submission_sha256"].map(_short_sha)
    if "normalized_submission_sha256" in df.columns:
        df["normalized_submission_sha256"] = df["normalized_submission_sha256"].map(_short_sha)

    out_paths.json_path.parent.mkdir(parents=True, exist_ok=True)
    out_paths.csv_path.parent.mkdir(parents=True, exist_ok=True)
    out_paths.html_path.parent.mkdir(parents=True, exist_ok=True)

    out_paths.json_path.write_text(df.to_json(orient="records", indent=2, double_precision=15), encoding="utf-8")
    df.to_csv(out_paths.csv_path, index=False, quoting=csv.QUOTE_MINIMAL, float_format="%.15g")

    out_paths.html_path.write_text(df.to_html(index=False, escape=True), encoding="utf-8")

    return df


def main() -> int:
    import argparse

    parser = argparse.ArgumentParser(description="Generate leaderboard files from the local results DB.")
    parser.add_argument("--db-path", default="results/results.sqlite")
    parser.add_argument("--competition-id", default=None)
    parser.add_argument("--per-competition", action="store_true", help="If set, leaderboard is filtered to --competition-id.")
    parser.add_argument("--write-root", action="store_true", help="If set, write LEADERBOARD.md/html at repo root.")
    parser.add_argument(
        "--import-results",
        action="store_true",
        help="If set, (re)import all `runs/*/result.json` into the DB before generating the leaderboard.",
    )
    parser.add_argument("--runs-root", default="runs", help="Path to the runs/ directory for --import-results.")
    args = parser.parse_args()

    repo_root = Path(__file__).resolve().parents[1]
    db_path = Path(args.db_path)

    if args.import_results:
        runs_root = Path(args.runs_root)
        imported = 0
        for run_dir in sorted(runs_root.glob("*")):
            if not run_dir.is_dir():
                continue
            result_path = run_dir / "result.json"
            if not result_path.exists():
                continue
            try:
                rr = read_result_json(result_path)
            except Exception:
                continue
            if args.per_competition and args.competition_id and rr.competition_id != args.competition_id:
                continue
            insert_run(db_path, rr)
            imported += 1
        print(f"imported results into DB: {imported}")

    out_paths = LeaderboardPaths(
        json_path=repo_root / "results" / "leaderboard.json",
        csv_path=repo_root / "results" / "leaderboard.csv",
        html_path=repo_root / "results" / "leaderboard.html",
    )
    df = build_leaderboard(
        db_path=db_path,
        out_paths=out_paths,
        competition_id=args.competition_id if args.per_competition else None,
    )
    if args.write_root:
        write_root_leaderboard(df=df, repo_root=repo_root)
    print(f"wrote: {out_paths.json_path}")
    print(f"wrote: {out_paths.csv_path}")
    print(f"wrote: {out_paths.html_path}")
    if args.write_root:
        print(f"wrote: {repo_root / 'LEADERBOARD.md'}")
        print(f"wrote: {repo_root / 'LEADERBOARD.html'}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
